import type { Project } from './project-types';
export const initialProjects:Project[]=[
 {id:'sprache-und-form',title:'Sprache als Form',category:'Objekt · Material · Sprache',summary:'Papier, Schrift und Holz verbinden sich zu einem Objekt zwischen Sitzmöbel und Erzählung.',body:'Die Werkgruppe untersucht das Zusammenspiel von Papier, Schrift und räumlicher Form. Gerolltes Material trägt die Sitzfläche; die beschriftete Hülle gibt dem Objekt eine zweite, sprachliche Ebene.\n\nDie unterschiedlichen Ansichten zeigen das Objekt mit Schrift, Büchern und als reduzierte Materialstudie. Die digitale Zerlegung macht seine konstruktiven Ebenen sichtbar. Das 3D-Modell ist eine angenäherte Rekonstruktion nach der Zerlegeansicht.',media:[{url:'/portfolio/language-object.webp',kind:'image',alt:'Papierobjekt mit mehrsprachigen Schriftzeichen'},{url:'/portfolio/chair.webp',kind:'image',alt:'Stuhlobjekt mit Papierstützen und geschwungener Lehne'},{url:'/portfolio/chair-books.webp',kind:'image',alt:'Stuhlobjekt mit aufgeschlagenen Büchern'},{url:'/portfolio/chair-exploded-reference.png',kind:'image',alt:'Zerlegeansicht mit Einzelteilen des Stuhls'}],published:true,position:0,updatedAt:''},
 {id:'sitzlandschaft',title:'Raum für Begegnung',category:'Außenraum · Sitzlandschaft',summary:'Holz, vorhandene Strukturen und blaue Sitzflächen verändern einen gemeinschaftlichen Außenraum.',body:'Eine Sitzlandschaft im Außenraum: Baumstämme und farbige Sitzflächen bilden unterschiedliche Orte zum Verweilen. Die Anordnung reagiert auf den vorhandenen Hof und schafft eine offene Gruppe statt einer einzelnen Sitzreihe.\n\nDas Projekt verbindet die Auseinandersetzung mit Material mit der Frage, wie Menschen einen gemeinsamen Raum nutzen.',media:[{url:'/portfolio/public-space.webp',kind:'image',alt:'Hof mit Baumstämmen und blauen Sitzflächen'}],published:true,position:1,updatedAt:''},
 {id:'malerei',title:'Farbe in Bewegung',category:'Malerei · Experiment',summary:'Gestische Linien, starke Kontraste und übereinanderliegende Farbfelder.',body:'Abstrakte Arbeiten zwischen fließender Geste und klar gegliederter Fläche. Rot, Pink, Grün und Blau entwickeln jeweils andere Spannungen.\n\nDie Werkgruppe zeigt unterschiedliche Ansätze: gerichtete Bewegung, überlagerte Linien und gegeneinander gesetzte Farbräume.',media:['painting-flow','painting-pink','painting-lines','painting-field'].map((n,i)=>({url:'/portfolio/'+n+'.webp',kind:'image' as const,alt:['Abstrakte Malerei mit roter und grüner Bewegung','Pink-grüne abstrakte Malerei','Mehrfarbige vertikale Linien','Komposition aus kontrastierenden Farbfeldern'][i]})),published:true,position:2,updatedAt:''},
 {id:'materialexperimente',title:'Spuren im Material',category:'Material · Oberfläche',summary:'Eine organische Oberflächenstudie mit Schichten, Rissen und Farbverläufen.',body:'Die Oberfläche wird selbst zum Untersuchungsfeld. Gelbe und violette Bereiche, unregelmäßige Linien und sichtbare Übergänge erzeugen eine organische Struktur.\n\nDie Arbeit ergänzt die Malereien um einen stärker auf Material und Oberfläche gerichteten Blick.',media:[{url:'/portfolio/material-study.webp',kind:'image',alt:'Gelbe organische Materialstudie mit violetten Bereichen und Risslinien'}],published:true,position:3,updatedAt:''},
 {id:'humanfaktoren',title:'Der Mensch als Maß',category:'Ergonomie · Humanfaktoren',summary:'Arbeitsplatzanalyse, Umgestaltung und Reflexion im Vergleich mit der DASA.',body:'Analyse — Der untersuchte Schreibtisch misst 87 cm in der Höhe, 122 cm in der Länge und 50 cm in der Tiefe. Die Dokumentation betrachtet die Abstimmung von Tisch, Stuhl und Arbeitsmitteln sowie Licht, Akustik und Raumklima.\n\nUmgestaltung — Der Hauptbildschirm wird zentral platziert, weitere Geräte stehen seitlich. Die Arbeitsfläche wird aufgeräumt und die Lampen werden für eine indirekte Ausleuchtung ausgerichtet.\n\nDASA-Vergleich — Ein Arbeitsplatz im Operationssaal dient als Vergleich: sitzende und stehende Tätigkeit, Bewegungsfreiheit, Pausengestaltung und Anforderungen an die Konzentration werden gegenübergestellt.',media:[],published:true,position:4,updatedAt:''},
 {id:'manguin',title:'Farbe statt Wirklichkeit',category:'Bildkopie · Fauvismus',summary:'Eine Auseinandersetzung mit Henri Manguins „Jeanne à l’ombrelle“: von der Analyse zur eigenen Bildkopie.',body:'Recherche — Untersuchung von Komposition, Linienführung und Farbkontrasten des Vorbilds.\n\nSkizzen — Die geschwungenen Baumstämme und die Position der Figur werden analysiert und auf die Leinwand übertragen.\n\nFarbtests — Orange, Blau und Grün stehen im Mittelpunkt der Mischversuche. Der Sonnenschirm soll als farblicher Blickfang wirken.\n\nMalprozess — Große Farbflächen bilden den Anfang. Darauf folgen präzisierte Formen, verstärkte Kontraste und weitere Farbschichten.\n\nReflexion — Die Arbeit untersucht, wie intensive, freie Farben Stimmung vermitteln können, ohne der realistischen Abbildung zu folgen.',media:[],published:true,position:5,updatedAt:''}
];
initialProjects[0].media.push(
 {url:'/portfolio/chair-turntable.mp4',kind:'video',alt:'3D-Ansicht des Stuhlprojekts — bereitgestellter Tripo-Showcase'},
 {url:'/portfolio/chair-parts-turntable.mp4',kind:'video',alt:'Einzelteile des Stuhls — bereitgestellter Tripo-Showcase'}
);
initialProjects[4].media=Array.from({length:4},(_,i)=>({url:`/portfolio/ergonomie-${i+1}.webp`,kind:'image',alt:['Arbeitsplatzaufnahme und ergonomische Bewertung','Analyse des Arbeitsumfelds','Umgestaltung des Arbeitsplatzes','DASA-Reflexion und Vergleich'][i]}));
initialProjects[5].media=Array.from({length:6},(_,i)=>({url:`/portfolio/manguin-${i+1}.webp`,kind:'image',alt:`Manguin-Projektdokumentation — Seite ${i+1}`}));
