"use client";
import { useState } from 'react';
import Link from 'next/link';
import type { Project } from '@/lib/project-types';
import { ChairScene } from './chair-scene';
import { Motion } from './motion';
import { PointerEffects } from './pointer-effects';

export function Portfolio({projects}:{projects:Project[]}){
 const [active,setActive]=useState(0);const featured=projects.filter(p=>p.media.length);const p=featured[active];
 return <><Motion/><PointerEffects/><header className="site-nav"><a className="brand" href="#start">HS<span> / HIDRIN SENO</span></a><nav aria-label="Hauptnavigation"><a href="#arbeiten">Arbeiten</a><a href="#identitaet">Identität</a><a href="#kontakt">Kontakt ↗</a></nav></header><main>
 <section className="hero" id="start"><div className="hero-meta"><span>INNENARCHITEKTUR × KUNST × TECHNOLOGIE</span><span>BIELEFELD / DETMOLD</span></div><h1 className="hero-title"><span>Raum wird</span><span><em>Geschichte.</em></span></h1><div className="hero-composition"><div className="hero-orbit"><ChairScene hero /></div><figure className="hero-painting"><img src="/portfolio/painting-flow.webp" alt="Abstrakte Malerei in Rot, Grün und Gelb"/></figure><div className="hero-caption"><span>HIDRIN ADEL SENO</span><p>Ich denke in Räumen.<br/>Ich experimentiere mit Material.<br/>Ich verbinde Welten.</p></div></div><a className="scroll-cue" href="#chair-story">SCROLLEN & ENTDECKEN <span>↓</span></a></section>
 <section id="chair-story" className="chair-story"><div className="chair-sticky"><div className="chair-title"><span className="eyebrow">01 / SPRACHE ALS FORM</span><h2>Ein Objekt.<br/><em>Viele Ebenen.</em></h2><p>Papier. Holz. Schrift.<br/>Bewege dich durch den Aufbau.</p></div><ChairScene/><div className="chair-note">3D-REKONSTRUKTION NACH DER PROJEKTREFERENZ</div></div><div className="story-steps"><article><span>01 — MATERIAL</span><h3>Aus Papier<br/>wird Struktur.</h3><p>Gerollte Stützen tragen die runde Sitzfläche. Das alltägliche Material erhält eine räumliche Aufgabe.</p></article><article><span>02 — SPRACHE</span><h3>Eine Oberfläche,<br/>viele Stimmen.</h3><p>Schrift umschließt das Objekt. Sprache wird sichtbar, greifbar und Teil seiner Form.</p></article><article><span>03 — ZUSAMMENSPIEL</span><h3>Die Teile erzählen<br/>das Ganze.</h3><Link className="button" href="/projekte/sprache-und-form">Zum Projekt ↗</Link></article></div></section>
 <section id="arbeiten" className="projects-section"><div className="section-heading" data-reveal><span className="eyebrow">02 / ARBEITEN</span><h2>Andere Materialien.<br/><em>Neue Perspektiven.</em></h2></div>{p&&<div className="spatial-slider" aria-roledescription="Karussell" aria-label="Ausgewählte Projekte"><div className="slider-controls"><span aria-live="polite">{String(active+1).padStart(2,'0')} / {String(featured.length).padStart(2,'0')}</span><div><button aria-label="Vorheriges Projekt" onClick={()=>setActive((active-1+featured.length)%featured.length)}>←</button><button aria-label="Nächstes Projekt" onClick={()=>setActive((active+1)%featured.length)}>→</button></div></div><div className="slider-stage">{featured.map((item,i)=><Link key={item.id} href={'/projekte/'+item.id} className={'spatial-card '+(i===active?'active':'')} aria-hidden={i!==active} tabIndex={i===active?0:-1} style={{transform:`translateX(${(i-active)*75}%) translateZ(${-Math.abs(i-active)*210}px) rotateY(${(i-active)*-18}deg)`,opacity:Math.abs(i-active)>1?0:1}}>{item.media[0].kind==='image'?<img src={item.media[0].url} alt={item.media[0].alt} loading="lazy"/>:<video src={item.media[0].url} muted playsInline preload="metadata"/>}<span>{item.title} ↗</span></Link>)}</div><div className="slider-description"><span className="eyebrow">{p.category}</span><h3>{p.title}</h3><p>{p.summary}</p></div></div>}<div className="all-projects">{projects.map((item,i)=><Link href={'/projekte/'+item.id} key={item.id}><span>{String(i+1).padStart(2,'0')}</span><h3>{item.title}</h3><small>{item.category}</small><b>↗</b></Link>)}</div></section>
 <section className="identity-section" id="identitaet"><span className="eyebrow">03 / IDENTITÄT</span><h2 data-reveal>Ich passe nicht<br/>in <em>eine Disziplin.</em></h2><div className="identity-grid"><p>Innenarchitektur ist mein Ausgangspunkt. Kunst, Informationstechnik, Handwerk und Sprache verändern meinen Blick darauf.</p><p>Seit September 2025 studiere ich an der Detmolder Schule für Gestaltung der TH OWL. Mich interessiert, wie Menschen Räume erleben — und wie Material und Technologie diese Erfahrung prägen.</p></div><div className="discipline-line" aria-hidden="true">RAUM / KUNST / TECHNIK / SPRACHE</div></section>
 <section className="lab-section" id="lab"><div data-reveal><span className="eyebrow">04 / DIGITAL LAB</span><h2>Werkzeuge zum<br/><em>Weiterdenken.</em></h2></div><div className="tools-grid">{[['Raum & Entwurf','Rhino 8 · Twinmotion · Rayon'],['Generative Gestaltung','Grasshopper · Creative Coding'],['Neue Experimente','Blender · TouchDesigner · Spline'],['Bild & Ausdruck','Photoshop · Fotografie · Malerei']].map(([title,body])=><article key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></section>
 <section className="experience-section"><span className="eyebrow">05 / ERFAHRUNG</span><h2 data-reveal>Wissen wächst<br/><em>durch Praxis.</em></h2><div className="timeline">{[['02–05 / 2026','Twistel, Bielefeld','Praktikum im Dachdecker- und Zimmererhandwerk. Konstruktion, Materialien und Baustellenpraxis.'],['06 / 2024 – 06 / 2025','Apollo Optik','Fachverkäuferin. Kundenberatung, Verkauf, Warenpräsentation und Service.'],['01–04 / 2024','POCO, Bielefeld','Kundenbetreuung, Verkauf und Unterstützung im Filialalltag.'],['08 / 2022','AVU Architekten','Freiwilliges Praktikum mit Einblicken in Büroabläufe und Projektaufgaben.'],['2020–2022','Informationstechnische Assistentin','Fachhochschulreife und Ausbildung am Carl-Severing-Berufskolleg, Bielefeld.'],['05–06 / 2020','U-ROB GmbH','Praktikum in Verwaltung und Büroorganisation.'],['02–03 / 2019','CSM Mein Systemhaus','Schulpraktikum in Warendorf.']].map(([date,title,body])=><article key={title}><span>{date}</span><div><h3>{title}</h3><p>{body}</p></div></article>)}</div></section>
 <section className="culture-section"><span className="eyebrow">06 / SPRACHE & KULTUR</span><h2 data-reveal>Mehr als eine<br/><em>Perspektive.</em></h2><div className="languages">{[['Kurdisch','Muttersprache'],['Arabisch','Sehr gute Kenntnisse'],['Deutsch','Sehr gute Kenntnisse'],['Englisch','Gute Kenntnisse']].map(([name,level])=><div key={name}><strong>{name}</strong><span>{level}</span></div>)}</div><p>Sprachen lernen, Fotografie, Design und Gestaltung verbinden meine Interessen über einzelne Disziplinen hinweg.</p></section>
 <section id="kontakt" className="contact-section"><span className="eyebrow">07 / EIN NEUES KAPITEL</span><h2 data-reveal>Lass uns<br/><em>Raum schaffen.</em></h2><a className="contact-mail" href="mailto:hidrin.seno@icloud.com">hidrin.seno@icloud.com ↗</a></section></main><footer><span>HIDRIN ADEL SENO · PORTFOLIO</span><a href="/admin">Admin</a><a href="#start">Nach oben ↑</a></footer></>;
}





